const masterBank={
    "Government": [
  {q: "The primary reason for the failure of the 1951 Macpherson Constitution was?", a: "Absence of a provision for central ministerial responsibility", options: ["Introduction of the elective principle", "Absence of a provision for central ministerial responsibility", "Exclusion of traditional rulers", "Creation of a unicameral legislature"]},
  {q: "In a presidential system, the 'Doctrine of Reciprocity' is best exemplified by?", a: "Senate confirmation of executive appointments", options: ["The President’s power to dissolve legislature", "Senate confirmation of executive appointments", "The judiciary's power of impeachment", "Creation of administrative tribunals"]},
  {q: "Which pre-colonial system practiced 'ordered anarchy'?", a: "The Segmentary lineage system of the Igbos", options: ["The Sokoto Caliphate", "The Old Oyo Empire", "The Segmentary lineage system of the Igbos", "The Benin Kingdom"]},
  {q: "The difference between 'De Jure' and 'De Facto' sovereign is?", a: "Legal recognition vs actual exercise of power", options: ["Military vs economic power", "Religious vs secular law", "Legal recognition vs actual exercise of power", "Internal vs external diplomacy"]},
  {q: "The 1976 Local Government Reforms were significant because they?", a: "Standardized functions and structure", options: ["Abolished the service commission", "Standardized functions and structure", "Introduced parliamentary system", "Handed revenue to the Federal govt"]},
  {q: "'Extra-Territoriality' in international law protects?", a: "Diplomatic premises and personnel", options: ["Refugees in war zones", "Diplomatic premises and personnel", "Multinational corporations", "International waters"]},
  {q: "Creating new states under the 1999 Constitution requires?", a: "A 2/3 majority in a referendum by the affected area", options: ["Approval by Council of State", "Simple majority in Supreme Court", "A 2/3 majority in a referendum by the affected area", "The President's sole proclamation"]},
  {q: "A fundamental disadvantage of a rigid constitution is?", a: "It may become obsolete in a changing society", options: ["Executive manipulation", "It may become obsolete in a changing society", "Frequent military intervention", "Ignores minority rights"]},
  {q: "The NCNC-NPC coalition of 1960 was necessitated by?", a: "Failure of any party to win an absolute majority", options: ["Threat of a military coup", "Failure of any party to win an absolute majority", "British Colonial Office directive", "Need to suppress the Action Group"]},
  {q: "An 'ultra vires' act of an administrative body is?", a: "Acting beyond powers conferred by statute", options: ["Refusing an unpopular law", "Acting beyond powers conferred by statute", "Consulting the judiciary", "Appointing a clerk"]},
  {q: "The 'Principle of Non-Intervention' in the AU is criticized because?", a: "It shields dictators from scrutiny", options: ["Encourages aid dependency", "It shields dictators from scrutiny", "Mandates single currency", "Gives UN power over borders"]},
  {q: "The 'Udoji Commission' of 1974 aimed to?", a: "Professionalize the civil service", options: ["Reduce civil servants", "Professionalize the civil service", "Abolish federal character", "Increase taxes"]},
  {q: "Gerontocracy is government by?", a: "Elders", options: ["The wealthy", "The military", "Elders", "Religious leaders"]},
  {q: "The 1922 Clifford Constitution was limited because?", a: "The Executive Council was entirely British", options: ["The Executive Council was entirely British", "Had no power to tax", "Was elected by the people", "Subordinate to regional governors"]},
  {q: "The 'Bolshevik Revolution' of 1917 led to?", a: "Communism", options: ["Fascism", "Communism", "Capitalism", "Nazism"]},
  {q: "Fascism originated in which country?", a: "Italy", options: ["Germany", "Italy", "Russia", "Spain"]},
  {q: "A major merit of a bicameral legislature is?", a: "Prevents hasty passage of bills", options: ["Is very cheap to run", "Prevents hasty passage of bills", "Eliminates political friction", "Favors the executive arm"]},
  {q: "The 'Rule of Law' is most limited by?", a: "State of Emergency", options: ["Judicial review", "State of Emergency", "Public opinion", "Multi-party system"]},
  {q: "The 'Great Purge' is associated with?", a: "Totalitarianism", options: ["Liberalism", "Feudalism", "Totalitarianism", "Confederalism"]},
  {q: "The head of the 'Judiciary' in Nigeria is?", a: "Chief Justice of Nigeria", options: ["Attorney General", "Chief Justice of Nigeria", "The Senate President", "The President"]},
  {q: "A state with one central source of authority is?", a: "Unitary", options: ["Federal", "Confederal", "Unitary", "Monarchy"]},
  {q: "Delegated legislation is checked by?", a: "Judicial Review", options: ["The Police", "Judicial Review", "The Civil Service", "The Electorate"]},
  {q: "The 'Ombudsman' in Nigeria is known as?", a: "Public Complaints Commission", options: ["EFCC", "Public Complaints Commission", "Code of Conduct Bureau", "ICPC"]},
  {q: "A formal written accusation of a public official is?", a: "Impeachment", options: ["Referendum", "Recall", "Impeachment", "Plebiscite"]},
  {q: "The AU headquarters is located in?", a: "Addis Ababa", options: ["Cairo", "Addis Ababa", "Lagos", "Nairobi"]},
  {q: "The first Nigerian President was?", a: "Dr. Nnamdi Azikiwe", options: ["Abubakar Tafawa Balewa", "Dr. Nnamdi Azikiwe", "Johnson Aguiyi-Ironsi", "Obafemi Awolowo"]},
  {q: "Which system gives the component units most power?", a: "Confederation", options: ["Federation", "Unitary", "Confederation", "Monarchy"]},
  {q: "The philosophy of 'Socialism' advocates for?", a: "State ownership of means of production", options: ["Private ownership", "State ownership of means of production", "Military rule", "No government"]},
  {q: "Pressure groups use 'Lobbying' to?", a: "Influence legislators", options: ["Win elections", "Influence legislators", "Appoint judges", "Arrest criminals"]},
  {q: "The 'Iron Law of Oligarchy' suggests?", a: "All organizations eventually become ruled by a few", options: ["The strongest survive", "All organizations eventually become ruled by a few", "Democracy is inevitable", "Monarchy is divine"]},
  {q: "Which Nigerian constitution introduced 'Federalism'?", a: "Lyttelton (1954)", options: ["Clifford (1922)", "Richards (1946)", "Macpherson (1951)", "Lyttelton (1954)"]},
  {q: "Who was the 'Chairman' of the 1977 Constituent Assembly?", a: "Justice Udo Udoma", options: ["Justice Elias", "Justice Udo Udoma", "Chief Rotimi Williams", "Dr. Nnamdi Azikiwe"]},
  {q: "Public corporations are funded by?", a: "The government", options: ["Shareholders", "The government", "NGOs", "Foreign banks"]},
  {q: "The principle of 'Anonymity' applies to?", a: "Civil Servants", options: ["Politicians", "Civil Servants", "Judges", "The Police"]},
  {q: "A country's foreign policy is mainly determined by?", a: "National Interest", options: ["International Law", "National Interest", "The UN", "Public Opinion"]},
  {q: "The 'Pre-colonial' Hausa-Fulani system was?", a: "Highly centralized", options: ["Decentralized", "Highly centralized", "A democracy", "A republic"]},
  {q: "The 'Ogboni' society in Yoruba land performed?", a: "Judicial and king-making roles", options: ["Only religious roles", "Military roles", "Judicial and king-making roles", "Only trade roles"]},
  {q: "The 'Age Grade' system was prominent in?", a: "Pre-colonial Igbo society", options: ["The Oyo Empire", "The Sokoto Caliphate", "Pre-colonial Igbo society", "The Benin Kingdom"]},
  {q: "A system with two legislative houses is?", a: "Bicameral", options: ["Unicameral", "Bicameral", "Diarchy", "Autocracy"]},
  {q: "The primary function of the legislature is?", a: "Law-making", options: ["Law interpretation", "Law-making", "Law enforcement", "Policy implementation"]},
  {q: "The 1963 Constitution made Nigeria a?", a: "Republic", options: ["Colony", "Monarchy", "Republic", "Protectorate"]},
  {q: "The highest court in the colonial era was?", a: "The West African Court of Appeal", options: ["The Supreme Court", "The West African Court of Appeal", "The Privy Council", "The High Court"]},
  {q: "Direct democracy is best practiced through?", a: "Referendums", options: ["Elections", "Referendums", "Lobbying", "Protests"]},
  {q: "A 'Coup d’etat' is an?", a: "Unconstitutional change of government", options: ["Election process", "Unconstitutional change of government", "Amendment of law", "Court ruling"]},
  {q: "Which organization replaced the OAU?", a: "African Union (AU)", options: ["ECOWAS", "African Union (AU)", "NEPAD", "ECOMOG"]},
  {q: "The power of a court to declare a law null and void is?", a: "Judicial Review", options: ["Prerogative writ", "Judicial Review", "Contempt of court", "Rule of law"]},
  {q: "The 'Cabinet' is a feature of?", a: "Parliamentary system", options: ["Presidential system", "Parliamentary system", "Military rule", "Absolute monarchy"]},
  {q: "The 'Electoral College' is used in?", a: "USA", options: ["Nigeria", "USA", "United Kingdom", "Ghana"]},
  {q: "The concept of 'Sovereignty' was popularized by?", a: "Jean Bodin", options: ["John Locke", "Jean Bodin", "Karl Marx", "A.V. Dicey"]},
  {q: "The 1999 Constitution is based on the?", a: "1979 Constitution", options: ["1960 Constitution", "1963 Constitution", "1979 Constitution", "1989 Constitution"]},
  {q: "A person who is not a citizen but lives in a country is?", a: "An alien", options: ["A refugee", "An alien", "A diplomat", "A nomad"]},
  {q: "The 'Cold War' ended with the fall of?", a: "The Soviet Union", options: ["The British Empire", "The Soviet Union", "The Roman Empire", "The Third Reich"]},
  {q: "Which country is NOT a member of OPEC?", a: "USA", options: ["Nigeria", "USA", "Saudi Arabia", "Venezuela"]},
  {q: "The 'Commonwealth' is made up of?", a: "Former British colonies", options: ["All European nations", "Former British colonies", "Oil-producing nations", "African nations"]},
  {q: "A 'Manifesto' is issued by?", a: "Political Parties", options: ["The Police", "Political Parties", "The Judiciary", "The Civil Service"]},
  {q: "The 'Judicial Service Commission' is responsible for?", a: "Appointing judges", options: ["Passing laws", "Appointing judges", "Collecting taxes", "Leading the army"]},
  {q: "A 'Unicameral' legislature has?", a: "One chamber", options: ["One chamber", "Two chambers", "Three chambers", "Four chambers"]},
  {q: "The 'Warrant Chiefs' were introduced in?", a: "Eastern Nigeria", options: ["Northern Nigeria", "Western Nigeria", "Eastern Nigeria", "Lagos Colony"]},
  {q: "Who was the first Nigerian Prime Minister?", a: "Abubakar Tafawa Balewa", options: ["Nnamdi Azikiwe", "Abubakar Tafawa Balewa", "Obafemi Awolowo", "Ahmadu Bello"]},
  {q: "The UN Security Council has how many permanent members?", a: "5", options: ["5", "10", "15", "20"]},
  {q: "The 'Bill of Rights' protects?", a: "Fundamental human rights", options: ["Government secrets", "Fundamental human rights", "The police force", "Trade agreements"]},
  {q: "A 'Confederation' is usually?", a: "Loose and weak at the center", options: ["Tight and strong at the center", "Loose and weak at the center", "A military dictatorship", "Led by a King"]},
  {q: "The 'Policy of Association' was used by?", a: "France", options: ["Britain", "France", "Portugal", "Belgium"]},
  {q: "The 1914 Amalgamation of Nigeria was done by?", a: "Lord Lugard", options: ["Lord Milverton", "Lord Lugard", "Sir Arthur Richards", "Sir John Macpherson"]},
  {q: "The 'National Assembly' consists of?", a: "Senate and House of Representatives", options: ["Senate and Governors", "Senate and House of Representatives", "President and Cabinet", "Judiciary and Police"]},
  {q: "A 'Franchise' is the?", a: "Right to vote", options: ["Right to own property", "Right to vote", "Duty to pay tax", "Freedom of movement"]},
  {q: "The 'Secretariat' is the administrative organ of?", a: "The United Nations", options: ["The United Nations", "The US Government", "The Nigerian Army", "Political Parties"]},
  {q: "The 'Referendum' is a form of?", a: "Direct democracy", options: ["Military decree", "Direct democracy", "Judicial ruling", "Executive order"]},
  {q: "The 'Lagos Youth Movement' was formed in?", a: "1934", options: ["1920", "1934", "1944", "1960"]},
  {q: "The 'NEPAD' stands for?", a: "New Partnership for Africa's Development", options: ["National Economic Plan for African Development", "New Partnership for Africa's Development", "Network of East Phased African Development", "New Plan for African Defense"]},
  {q: "A 'Constitution' that is easy to change is?", a: "Flexible", options: ["Rigid", "Flexible", "Written", "Unwritten"]},
  {q: "The 'Sokoto Caliphate' used which system?", a: "Theocratic", options: ["Democratic", "Theocratic", "Republican", "Secular"]},
  {q: "The 'Magna Carta' of 1215 is related to?", a: "The Rule of Law", options: ["The French Revolution", "The Rule of Law", "The Nigerian Independence", "The US Civil War"]},
  {q: "The 'Electorate' refers to?", a: "Qualified voters", options: ["Elected officials", "Qualified voters", "Political candidates", "Polling agents"]},
  {q: "Which agency handles elections in Nigeria?", a: "INEC", options: ["NPC", "INEC", "EFCC", "ICPC"]},
  {q: "The 'Veto' power in the UN is used by?", a: "Permanent members of the Security Council", options: ["All member states", "Permanent members of the Security Council", "The Secretary-General", "The General Assembly"]},
  {q: "A 'Unitary' system is most effective in?", a: "Small, homogeneous states", options: ["Large, diverse states", "Small, homogeneous states", "Global empires", "Confederations"]},
  {q: "Who was the 'Father of the Nigerian Constitution'?", a: "Chief Rotimi Williams", options: ["Herbert Macaulay", "Chief Rotimi Williams", "Nnamdi Azikiwe", "Obafemi Awolowo"]},
  {q: "The 'Minority Commission' of 1958 was headed by?", a: "Willink", options: ["Richards", "Willink", "Clifford", "Bourdillon"]},
  {q: "The 'Nationalist Movement' aimed at?", a: "Ending colonial rule", options: ["Supporting the King", "Ending colonial rule", "Joining the UN", "Building roads"]},
  {q: "A 'Censure' motion is used to?", a: "Criticize or remove a minister", options: ["Pass a law", "Criticize or remove a minister", "Approve a budget", "Declare war"]},
  {q: "The '1989 Constitution' was meant for the?", a: "Third Republic", options: ["First Republic", "Second Republic", "Third Republic", "Fourth Republic"]},
  {q: "The 'Judiciary' maintains independence through?", a: "Security of tenure", options: ["Political appointments", "Security of tenure", "Control of the army", "Making laws"]},
  {q: "The 'ECOWAS' treaty was signed in?", a: "1975", options: ["1960", "1975", "1980", "1999"]},
  {q: "A 'By-election' occurs when?", a: "A seat becomes vacant mid-term", options: ["The whole parliament dissolves", "A seat becomes vacant mid-term", "A new country is formed", "The President resigns"]},
  {q: "The 'Richards Constitution' introduced?", a: "Regionalism", options: ["Independence", "Regionalism", "Unitary system", "The President"]},
  {q: "The 'Universal Declaration of Human Rights' was in?", a: "1948", options: ["1918", "1945", "1948", "1960"]},
  {q: "The 'Public Service' consists of?", a: "Government ministries and agencies", options: ["Only the military", "Government ministries and agencies", "Private companies", "Political parties"]},
  {q: "The 'Separation of Powers' was proposed by?", a: "Montesquieu", options: ["Hobbes", "Montesquieu", "Locke", "Marx"]},
  {q: "A 'Coalition' government is formed by?", a: "Two or more parties", options: ["The army", "Two or more parties", "The King", "A single party"]},
  {q: "The 'FCT' was moved from Lagos to Abuja in?", a: "1991", options: ["1976", "1980", "1991", "1999"]},
  {q: "The 'ICJ' is located in?", a: "The Hague", options: ["New York", "London", "The Hague", "Geneva"]},
  {q: "The '1999 Constitution' is the basis of the?", a: "Fourth Republic", options: ["First Republic", "Second Republic", "Third Republic", "Fourth Republic"]},
  {q: "The 'National Council of State' advises?", a: "The President", options: ["The Senate", "The President", "The Governor", "The Police"]},
  {q: "A 'Statute' is a law made by?", a: "The Legislature", options: ["The King", "The Legislature", "The Police", "The Judiciary"]},
  {q: "The 'Civil Service Commission' ensures?", a: "Merit-based recruitment", options: ["Winning elections", "Merit-based recruitment", "Military discipline", "Judicial fairness"]},
  {q: "The 'Oyo Mesi' could remove an?", a: "Alaafin", options: ["Emir", "Alaafin", "Oba", "Obi"]},
  {q: "The '1960 Independence' was granted by?", a: "The British Parliament", options: ["The UN", "The British Parliament", "The US Government", "The Nigerian Army"]},
  {q: "The 'Executive' arm is responsible for?", a: "Executing laws", options: ["Making laws", "Executing laws", "Interpreting laws", "Arresting people"]},
  {q: "The 'Freedom of Information' act promotes?", a: "Transparency", options: ["Secrecy", "Transparency", "Censorship", "Propaganda"]}
 ],
  "English": [
  {q: "The lawyer's argument was **specious**. (Synonym)", a: "Plausible but false", options: ["Deeply moving", "Plausible but false", "Logically sound", "Extremely brief"]},
  {q: "The manager was **parsimonious**. (Opposite)", a: "Extravagant", options: ["Cruel", "Extravagant", "Quiet", "Careful"]},
  {q: "They acted in **collusion** with the guard. (Meaning)", a: "Secret agreement for fraud", options: ["Physical combat", "Secret agreement for fraud", "Direct opposition", "Absence of witnesses"]},
  {q: "Hardly had the meeting started ___ the lights went out.", a: "when", options: ["than", "when", "then", "before"]},
  {q: "The professor's lecture was **abstruse**. (Synonym)", a: "Recondite", options: ["Clear", "Recondite", "Boring", "Loud"]},
  {q: "By the time the police arrived, the thieves ___.", a: "had fled", options: ["have fled", "fled", "had fled", "were fleeing"]},
  {q: "She is one of those people who ___ always complaining.", a: "are", options: ["is", "are", "was", "has"]},
  {q: "The judge was **disinterested** in the case. (Synonym)", a: "Impartial", options: ["Bored", "Impartial", "Corrupt", "Uninvolved"]},
  {q: "The CEO decided to **curtail** expenses. (Opposite)", a: "Augment", options: ["Reduce", "Augment", "Review", "Ignore"]},
  {q: "The suspect was caught **red-handed**. (Meaning)", a: "In the act", options: ["With blood on hands", "In the act", "While running", "Because of a tip"]},
  {q: "Neither of the candidates ___ qualified.", a: "is", options: ["is", "are", "were", "have been"]},
  {q: "His **ephemeral** success didn't last. (Synonym)", a: "Evanescent", options: ["Huge", "Evanescent", "Permanent", "Financial"]},
  {q: "The boy's story was **cock and bull**. (Meaning)", a: "Absurd", options: ["About animals", "Interesting", "Absurd", "Confident"]},
  {q: "The heavy rain **precluded** our departure. (Synonym)", a: "Prevented", options: ["Delayed", "Prevented", "Encouraged", "Witnessed"]},
  {q: "No sooner had the whistle blown ___ the race started.", a: "than", options: ["when", "than", "then", "and"]},
  {q: "The decision was **unanimous**. (Meaning)", a: "Agreed by all", options: ["Rejected by all", "Agreed by all", "Voted by half", "Made in secret"]},
  {q: "He is **adept** at the piano. (Opposite)", a: "Maladroit", options: ["Skilled", "Maladroit", "Fast", "Consistent"]},
  {q: "The new law is aimed at **mitigating** poverty. (Synonym)", a: "Alleviating", options: ["Increasing", "Alleviating", "Studying", "Ignoring"]},
  {q: "I look forward to ___ you.", a: "meeting", options: ["meet", "meeting", "have met", "be meeting"]},
  {q: "The building was **razed** to the ground. (Meaning)", a: "Completely destroyed", options: ["Built up", "Completely destroyed", "Painted", "Cleaned"]},
  {q: "Which is correctly spelt?", a: "Manoeuvre", options: ["Manuever", "Manoeuvre", "Manouvre", "Manoever"]},
  {q: "The meeting was adjourned **sine die**. (Meaning)", a: "Without a date for resumption", options: ["Until tomorrow", "Indefinitely", "Without a date for resumption", "For lunch"]},
  {q: "He is the **black sheep** of the family. (Meaning)", a: "A disgraced member", options: ["The favorite child", "A disgraced member", "The eldest son", "A successful person"]},
  {q: "The information is **redundant**. (Synonym)", a: "Superfluous", options: ["Important", "Superfluous", "Secret", "Scanty"]},
  {q: "The teacher's voice was **audible**. (Opposite)", a: "Inaudible", options: ["Loud", "Inaudible", "Soft", "Clear"]},
  {q: "She has been working here ___ five years.", a: "for", options: ["since", "for", "from", "at"]},
  {q: "The project was **aborted**. (Meaning)", a: "Stopped before completion", options: ["Successful", "Stopped before completion", "Delayed", "Celebrated"]},
  {q: "The man is **versatile**. (Synonym)", a: "Multi-talented", options: ["Lazy", "Multi-talented", "Wealthy", "Strong"]},
  {q: "He is a **voracious** reader. (Meaning)", a: "Very eager", options: ["Very slow", "Very eager", "A bored reader", "A blind reader"]},
  {q: "The cake was shared ___ the twelve boys.", a: "among", options: ["between", "among", "with", "for"]},
  {q: "If I ___ a bird, I would fly.", a: "were", options: ["am", "was", "were", "be"]},
  {q: "The sun ___ at 6 AM today.", a: "rose", options: ["rise", "rises", "rose", "risen"]},
  {q: "He is **honest**, ___?", a: "isn't he", options: ["is he", "isn't he", "doesn't he", "not so"]},
  {q: "I prefer coffee ___ tea.", a: "to", options: ["than", "to", "more than", "over"]},
  {q: "The boy is **meticulous**. (Opposite)", a: "Sloppy", options: ["Careful", "Sloppy", "Fast", "Quiet"]},
  {q: "He **hit the nail on the head**. (Meaning)", a: "Spoke the exact truth", options: ["Built a house", "Spoke the exact truth", "Was very angry", "Failed an exam"]},
  {q: "The weather is **clement**. (Synonym)", a: "Mild", options: ["Harsh", "Mild", "Rainy", "Cold"]},
  {q: "She is **industrious**. (Synonym)", a: "Hardworking", options: ["Lazy", "Hardworking", "Rich", "Pretty"]},
  {q: "I haven't seen her ___ Christmas.", a: "since", options: ["for", "since", "from", "at"]},
  {q: "The food was **insipid**. (Synonym)", a: "Tasteless", options: ["Delicious", "Tasteless", "Salty", "Spicy"]},
  {q: "He **turned a deaf ear** to my plea. (Meaning)", a: "Ignored me", options: ["Listened carefully", "Ignored me", "Was sick", "Laughed at me"]},
  {q: "Which is a verb?", a: "Analyze", options: ["Analysis", "Analytic", "Analyze", "Analyst"]},
  {q: "The match was **called off**. (Meaning)", a: "Cancelled", options: ["Postponed", "Cancelled", "Started", "Won"]},
  {q: "He is the **tallest** ___ the three.", a: "of", options: ["among", "between", "of", "from"]},
  {q: "The news ___ shocking.", a: "was", options: ["was", "were", "are", "have been"]},
  {q: "She **takes after** her mother. (Meaning)", a: "Resembles", options: ["Follows", "Resembles", "Hates", "Obeys"]},
  {q: "The room was **congested**. (Opposite)", a: "Spacious", options: ["Crowded", "Spacious", "Dirty", "Hot"]},
  {q: "He is **bold**, ___ he?", a: "isn't", options: ["is", "isn't", "was", "has"]},
  {q: "The boy apologized ___ his mistake.", a: "for", options: ["to", "for", "at", "with"]},
  {q: "It’s high time we ___.", a: "left", options: ["leave", "left", "leaving", "to leave"]},
  {q: "The man is **affluent**. (Synonym)", a: "Wealthy", options: ["Poor", "Wealthy", "Strong", "Old"]},
  {q: "He **came by** a rare coin. (Meaning)", a: "Obtained", options: ["Lost", "Obtained", "Sold", "Cleaned"]},
  {q: "The water is **potable**. (Meaning)", a: "Safe to drink", options: ["Hot", "Safe to drink", "Dirty", "Salty"]},
  {q: "Which is correctly spelt?", a: "Occurrence", options: ["Ocurrence", "Occurrence", "Occurence", "Occurance"]},
  {q: "He acts as if he ___ a millionaire.", a: "were", options: ["is", "was", "were", "be"]},
  {q: "The project is **mandatory**. (Synonym)", a: "Compulsory", options: ["Optional", "Compulsory", "Free", "Hard"]},
  {q: "He **passed out** in the heat. (Meaning)", a: "Fainted", options: ["Died", "Fainted", "Left", "Slept"]},
  {q: "I would rather you ___ here.", a: "stayed", options: ["stay", "stayed", "staying", "to stay"]},
  {q: "The child is **docile**. (Synonym)", a: "Compliant", options: ["Stubborn", "Compliant", "Wild", "Strong"]},
  {q: "The wind **blew out** the candle. (Meaning)", a: "Extinguished", options: ["Lighted", "Extinguished", "Moved", "Broke"]},
  {q: "She is **adept** at chess. (Synonym)", a: "Skilled", options: ["Lazy", "Skilled", "Poor", "Slow"]},
  {q: "The box is **heavy**, ___ it?", a: "isn't", options: ["is", "isn't", "has", "was"]},
  {q: "I saw a ___ of bees.", a: "swarm", options: ["pack", "swarm", "herd", "flock"]},
  {q: "He is **notorious** for theft. (Meaning)", a: "Well-known for bad deeds", options: ["Famous", "Well-known for bad deeds", "Quiet", "Innocent"]},
  {q: "The mountain is **colossal**. (Synonym)", a: "Huge", options: ["Small", "Huge", "Cold", "Far"]},
  {q: "I am used ___ late.", a: "to working", options: ["to work", "to working", "work", "working"]},
  {q: "The boy **broke down** in tears. (Meaning)", a: "Started crying", options: ["Stopped crying", "Started crying", "Fell down", "Laughed"]},
  {q: "Neither the man nor his wife ___.", a: "is coming", options: ["is coming", "are coming", "were coming", "have come"]},
  {q: "The journey was **tedious**. (Synonym)", a: "Tiring", options: ["Exciting", "Tiring", "Short", "Fast"]},
  {q: "He is **brave**. (Opposite)", a: "Cowardly", options: ["Strong", "Cowardly", "Fast", "Smart"]},
  {q: "The meeting **lasted** for an hour.", a: "lasted", options: ["last", "lasted", "lasts", "lasting"]},
  {q: "Which is correctly spelt?", a: "Commitment", options: ["Comitment", "Commitment", "Comittment", "Committment"]},
  {q: "He is the **best** of the two. (Corrected)", a: "Better", options: ["Best", "Better", "Good", "Most good"]},
  {q: "The car **broke down**. (Meaning)", a: "Stopped working", options: ["Crashed", "Stopped working", "Was sold", "Was painted"]},
  {q: "She is as **pretty** as a picture. (Synonym)", a: "Beautiful", options: ["Ugly", "Beautiful", "Smart", "Young"]},
  {q: "I don't have ___ money.", a: "any", options: ["some", "any", "many", "few"]},
  {q: "The man is **indigent**. (Synonym)", a: "Poor", options: ["Wealthy", "Poor", "Healthy", "Smart"]},
  {q: "He **gave up** smoking. (Meaning)", a: "Stopped", options: ["Started", "Stopped", "Enjoyed", "Hidden"]},
  {q: "The plane **took off**. (Meaning)", a: "Left the ground", options: ["Crashed", "Left the ground", "Landed", "Fixed"]},
  {q: "She is **obsessed** ___ music.", a: "with", options: ["at", "with", "for", "by"]},
  {q: "He is the **owner** of the car, ___ he?", a: "isn't", options: ["is", "isn't", "doesn't", "was"]},
  {q: "The work is **onerous**. (Synonym)", a: "Burdensome", options: ["Easy", "Burdensome", "Quick", "Fun"]},
  {q: "He **fell out** with his friend. (Meaning)", a: "Quarreled", options: ["Traveled", "Quarreled", "Played", "Met"]},
  {q: "The fruit is **ripe**. (Opposite)", a: "Unripe", options: ["Sweet", "Unripe", "Hard", "Red"]},
  {q: "I will **see to** it. (Meaning)", a: "Attend to", options: ["Ignore", "Attend to", "Look at", "Forget"]},
  {q: "The boy is **active**. (Opposite)", a: "Lethargic", options: ["Fast", "Lethargic", "Strong", "Smart"]},
  {q: "She **put off** the meeting. (Meaning)", a: "Postponed", options: ["Started", "Postponed", "Cancelled", "Held"]},
  {q: "Which is a noun?", a: "Ability", options: ["Able", "Ably", "Ability", "Abled"]},
  {q: "The sun **sets** in the West.", a: "sets", options: ["set", "sets", "setting", "setted"]},
  {q: "He is **friendly**. (Synonym)", a: "Amiable", options: ["Hostile", "Amiable", "Quiet", "Mean"]},
  {q: "I **ran into** him. (Meaning)", a: "Met by chance", options: ["Hit him", "Met by chance", "Saw him", "Chased him"]},
  {q: "The path is **narrow**. (Opposite)", a: "Wide", options: ["Thin", "Wide", "Long", "Straight"]},
  {q: "He **brought up** the idea. (Meaning)", a: "Introduced", options: ["Cancelled", "Introduced", "Forgot", "Finished"]},
  {q: "The tea is **hot**. (Opposite)", a: "Cold", options: ["Sweet", "Cold", "Warm", "Dark"]},
  {q: "She **look after** the kids. (Meaning)", a: "Cares for", options: ["Hates", "Cares for", "Sees", "Follows"]},
  {q: "He is **honest**. (Opposite)", a: "Deceitful", options: ["Pure", "Deceitful", "Smart", "Quiet"]},
  {q: "Which is correctly spelt?", a: "Privilege", options: ["Priviledge", "Privilege", "Privelege", "Privillage"]},
  {q: "He **made up** a story. (Meaning)", a: "Invented", options: ["Read", "Invented", "Forgot", "Told"]},
  {q: "The bag is **light**. (Opposite)", a: "Heavy", options: ["Dark", "Heavy", "Small", "Empty"]},
  {q: "I **look forward** to the trip.", a: "look forward", options: ["looking forward", "look forward", "looked forward", "looks forward"]}
],
  "Literature": [
  {q: "Mimicking a style for comedy is a?", a: "Parody", options: ["Satire", "Parody", "Pastiche", "Burlesque"]},
  {q: "A 'Sestet' is a stanza of?", a: "Six lines", options: ["Four lines", "Six lines", "Eight lines", "Two lines"]},
  {q: "Repeating a phrase at the start of clauses is?", a: "Anaphora", options: ["Epistrophe", "Anaphora", "Chiasmus", "Alliteration"]},
  {q: "Starting a story 'in the middle' is?", a: "In medias res", options: ["Prologue", "In medias res", "Flashback", "Epilogue"]},
  {q: "A single word applying to two others in different senses is?", a: "Zeugma", options: ["Onomatopoeia", "Zeugma", "Oxymoron", "Synecdoche"]},
  {q: "A character with low social class adventures is?", a: "Picaresque", options: ["Romantic", "Picaresque", "Gothic", "Epic"]},
  {q: "A natural pause in a line of verse is a?", a: "Caesura", options: ["Enjambment", "Caesura", "Rhyme", "Foot"]},
  {q: "Excessive pride leading to downfall is?", a: "Hubris", options: ["Hubris", "Hamartia", "Catharsis", "Nemesis"]},
  {q: "Unrhymed iambic pentameter is?", a: "Blank Verse", options: ["Free Verse", "Blank Verse", "Sonnet", "Ballad"]},
  {q: "The 'turning point' in a tragedy is?", a: "Peripeteia", options: ["Anagnorisis", "Peripeteia", "Climax", "Resolution"]},
  {q: "Moment of discovery for a hero is?", a: "Anagnorisis", options: ["Anagnorisis", "Catharsis", "Hamartia", "Hubris"]},
  {q: "Substitution of name for attribute (e.g., 'the Crown')?", a: "Metonymy", options: ["Synecdoche", "Metonymy", "Allusion", "Symbol"]},
  {q: "Part for the whole (e.g., 'all hands')?", a: "Synecdoche", options: ["Metonymy", "Synecdoche", "Irony", "Simile"]},
  {q: "Funny scene in tragedy to relieve tension?", a: "Comic relief", options: ["Comic relief", "Farce", "Satire", "Irony"]},
  {q: "Stereotyped character?", a: "Stock character", options: ["Main character", "Stock character", "Villain", "Hero"]},
  {q: "Narrator who knows all thoughts?", a: "Omniscient", options: ["Unreliable", "Omniscient", "First-person", "Objective"]},
  {q: "Poem about rural or shepherd life?", a: "Pastoral", options: ["Epic", "Pastoral", "Elegy", "Ode"]},
  {q: "Sudden realization in a story?", a: "Epiphany", options: ["Climax", "Epiphany", "Conflict", "Theme"]},
  {q: "Play that ends in disaster?", a: "Tragedy", options: ["Comedy", "Tragedy", "Farce", "Mime"]},
  {q: "A 14-line poem is a?", a: "Sonnet", options: ["Ode", "Elegy", "Sonnet", "Epic"]},
  {q: "Comparison using 'like' or 'as'?", a: "Simile", options: ["Metaphor", "Simile", "Personification", "Hyperbole"]},
  {q: "Giving human traits to objects?", a: "Personification", options: ["Irony", "Personification", "Sarcasm", "Metonymy"]},
  {q: "Exaggeration for emphasis?", a: "Hyperbole", options: ["Litotes", "Hyperbole", "Euphemism", "Metonymy"]},
  {q: "A mourning poem for the dead?", a: "Elegy", options: ["Elegy", "Ode", "Lyric", "Sonnet"]},
  {q: "Sequence of events in a story?", a: "Plot", options: ["Theme", "Plot", "Setting", "Style"]},
  {q: "Reference to a historical event?", a: "Allusion", options: ["Allusion", "Illusion", "Imagery", "Paradox"]},
  {q: "Contradictory words side by side?", a: "Oxymoron", options: ["Paradox", "Oxymoron", "Irony", "Pun"]},
  {q: "Statement that is true but contradictory?", a: "Paradox", options: ["Paradox", "Oxymoron", "Simile", "Irony"]},
  {q: "Central idea of a work?", a: "Theme", options: ["Theme", "Plot", "Climax", "Mood"]},
  {q: "Location and time of a story?", a: "Setting", options: ["Setting", "Plot", "Atmosphere", "Context"]},
  {q: "Audience knows more than characters?", a: "Dramatic Irony", options: ["Verbal Irony", "Dramatic Irony", "Sarcasm", "Paradox"]},
  {q: "Words imitating sounds?", a: "Onomatopoeia", options: ["Alliteration", "Onomatopoeia", "Assonance", "Rhythm"]},
  {q: "Mild word for a harsh one?", a: "Euphemism", options: ["Euphemism", "Hyperbole", "Irony", "Litotes"]},
  {q: "Character opposing the protagonist?", a: "Antagonist", options: ["Villain", "Antagonist", "Foil", "Clown"]},
  {q: "Understated statement using negative?", a: "Litotes", options: ["Hyperbole", "Litotes", "Metaphor", "Pun"]},
  {q: "Characters represent abstract qualities?", a: "Allegory", options: ["Allegory", "Fable", "Parable", "Myth"]},
  {q: "Animal story with a lesson?", a: "Fable", options: ["Myth", "Fable", "Legend", "Epic"]},
  {q: "Highest point of tension?", a: "Climax", options: ["Exposition", "Climax", "Resolution", "Conflict"]},
  {q: "Resolution of a dramatic plot?", a: "Denouement", options: ["Conflict", "Denouement", "Climax", "Prologue"]},
  {q: "Play without spoken words?", a: "Mime", options: ["Farce", "Mime", "Opera", "Musical"]},
  {q: "Repetition of vowel sounds?", a: "Assonance", options: ["Alliteration", "Assonance", "Consonance", "Rhyme"]},
  {q: "Mixes tragic and comic elements?", a: "Tragi-comedy", options: ["Melodrama", "Tragi-comedy", "Farce", "Satire"]},
  {q: "Stanza of three lines?", a: "Tercet", options: ["Couplet", "Tercet", "Quatrain", "Sestet"]},
  {q: "Stanza of four lines?", a: "Quatrain", options: ["Couplet", "Quatrain", "Octave", "Sonnet"]},
  {q: "Excessive emotion and suspense?", a: "Melodrama", options: ["Comedy", "Melodrama", "Satire", "Epic"]},
  {q: "Humor used to criticize social vice?", a: "Satire", options: ["Irony", "Satire", "Sarcasm", "Farce"]},
  {q: "Voice in a poem?", a: "Persona", options: ["Author", "Persona", "Narrator", "Character"]},
  {q: "Character who changes internally?", a: "Dynamic", options: ["Static", "Dynamic", "Flat", "Round"]},
  {q: "Character who stays the same?", a: "Static", options: ["Static", "Dynamic", "Protagonist", "Hero"]},
  {q: "Direct address to absent person?", a: "Apostrophe", options: ["Allusion", "Apostrophe", "Simile", "Metaphor"]},
  {q: "Introduction to a play?", a: "Prologue", options: ["Epilogue", "Prologue", "Chorus", "Scene"]},
  {q: "Concluding speech of a play?", a: "Epilogue", options: ["Prologue", "Epilogue", "Dialogue", "Climax"]},
  {q: "A play on words?", a: "Pun", options: ["Pun", "Irony", "Joke", "Metaphor"]},
  {q: "Emotional atmosphere of a work?", a: "Mood", options: ["Theme", "Mood", "Style", "Tone"]},
  {q: "Writer's attitude?", a: "Tone", options: ["Mood", "Tone", "Diction", "Imagery"]},
  {q: "Choice of words?", a: "Diction", options: ["Syntax", "Diction", "Imagery", "Style"]},
  {q: "Recurring element or idea?", a: "Motif", options: ["Theme", "Motif", "Symbol", "Plot"]},
  {q: "Object representing an idea?", a: "Symbol", options: ["Metaphor", "Symbol", "Motif", "Image"]},
  {q: "Mental pictures with words?", a: "Imagery", options: ["Diction", "Imagery", "Symbolism", "Metaphor"]},
  {q: "Struggle between opposing forces?", a: "Conflict", options: ["Climax", "Conflict", "Plot", "Theme"]},
  {q: "Line continues without pause?", a: "Enjambment", options: ["Caesura", "Enjambment", "Meter", "Stanza"]},
  {q: "Two rhyming lines?", a: "Couplet", options: ["Couplet", "Tercet", "Quatrain", "Sonnet"]},
  {q: "Highlights traits by contrast?", a: "Foil", options: ["Antagonist", "Foil", "Hero", "Villain"]},
  {q: "Pattern of rhymes?", a: "Rhyme scheme", options: ["Rhythm", "Meter", "Rhyme scheme", "Verse"]},
  {q: "Error leading to downfall?", a: "Hamartia", options: ["Hubris", "Hamartia", "Catharsis", "Conflict"]},
  {q: "Poem without regular rhyme/meter?", a: "Free verse", options: ["Blank verse", "Free verse", "Ode", "Epic"]},
  {q: "Poem meant to be sung?", a: "Ballad", options: ["Ode", "Ballad", "Elegy", "Sonnet"]},
  {q: "One-dimensional character?", a: "Flat", options: ["Flat", "Round", "Hero", "Narrator"]},
  {q: "Complex, developed character?", a: "Round", options: ["Flat", "Round", "Evil", "Boring"]},
  {q: "Writes a play?", a: "Playwright", options: ["Author", "Poet", "Playwright", "Novelist"]},
  {q: "Long speech by one character?", a: "Monologue", options: ["Dialogue", "Monologue", "Aside", "Soliloquy"]},
  {q: "Sentences and paragraphs writing?", a: "Prose", options: ["Poetry", "Drama", "Prose", "Epic"]},
  {q: "Self-written biography?", a: "Autobiography", options: ["Biography", "Autobiography", "Memoir", "Diary"]},
  {q: "Clues to future events?", a: "Foreshadowing", options: ["Flashback", "Foreshadowing", "Irony", "Imagery"]},
  {q: "Interruption to show past?", a: "Flashback", options: ["Foreshadowing", "Flashback", "Prologue", "Climax"]},
  {q: "Short writing on a subject?", a: "Essay", options: ["Novel", "Essay", "Short story", "Poem"]},
  {q: "Ending of a tragedy?", a: "Catastrophe", options: ["Denouement", "Catastrophe", "Epilogue", "Climax"]},
  {q: "Third-person pronouns?", a: "He, she, they", options: ["I, me, we", "You", "He, she, they", "Us"]},
  {q: "Arrangement of words?", a: "Syntax", options: ["Diction", "Syntax", "Style", "Rhythm"]},
  {q: "Rhythmic pattern of a poem?", a: "Meter", options: ["Meter", "Rhyme", "Stanza", "Foot"]},
  {q: "Poem in praise of something?", a: "Ode", options: ["Elegy", "Ode", "Epic", "Sonnet"]},
  {q: "Character lacking heroism?", a: "Anti-hero", options: ["Villain", "Protagonist", "Anti-hero", "Foil"]},
  {q: "Story explaining nature/origin?", a: "Myth", options: ["Myth", "Fable", "Short story", "Novel"]},
  {q: "Two rhyming iambic pentameter lines?", a: "Heroic couplet", options: ["Blank verse", "Heroic couplet", "Sonnet", "Quatrain"]},
  {q: "Drama with song and dance?", a: "Opera", options: ["Opera", "Drama", "Prose", "Fable"]},
  {q: "Literal meaning of a word?", a: "Denotation", options: ["Connotation", "Denotation", "Symbolism", "Diction"]},
  {q: "Implied meaning of a word?", a: "Connotation", options: ["Connotation", "Denotation", "Metaphor", "Image"]},
  {q: "Epic poem about a hero?", a: "Epic", options: ["Epic", "Lyric", "Ballad", "Sonnet"]},
  {q: "Historical story handed down?", a: "Legend", options: ["Legend", "Fable", "Myth", "Novel"]},
  {q: "A short poem about feelings?", a: "Lyric", options: ["Lyric", "Epic", "Ballad", "Ode"]},
  {q: "Repetition of consonant sounds?", a: "Alliteration", options: ["Assonance", "Alliteration", "Rhyme", "Meter"]},
  {q: "The person telling the story?", a: "Narrator", options: ["Author", "Narrator", "Protagonist", "Editor"]},
  {q: "A play meant for comedy?", a: "Comedy", options: ["Tragedy", "Comedy", "Drama", "Opera"]},
  {q: "Main character is also the?", a: "Protagonist", options: ["Antagonist", "Protagonist", "Villain", "Foil"]},
  {q: "Address to an object?", a: "Apostrophe", options: ["Allusion", "Apostrophe", "Simile", "Metaphor"]},
  {q: "Writing about one's own life?", a: "Autobiography", options: ["Biography", "Autobiography", "Memoir", "Essay"]},
  {q: "Hinting at what comes next?", a: "Foreshadowing", options: ["Flashback", "Foreshadowing", "Irony", "Conflict"]},
  {q: "The atmosphere created?", a: "Mood", options: ["Theme", "Mood", "Plot", "Setting"]},
  {q: "The message of the story?", a: "Theme", options: ["Theme", "Plot", "Climax", "Scene"]},
  {q: "The end of the story?", a: "Resolution", options: ["Climax", "Resolution", "Conflict", "Plot"]}
]

}